---
title: "Homework5_RChiaverini"
output:
  pdf_document: default
  html_document: default
date: '2022-11-25'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(ggthemes)
library(tidyverse)
library(lubridate)
library(nplyr)
homicides <- read_csv("homicide-data.csv")
```

## Making Graphs

```{r}
#creating separate y,m,d#
homicides_baltimore <- homicides %>% 
  mutate(city_name = str_c(city, state, sep = ",")) %>% 
  mutate(year = str_sub(reported_date, start = 1, end = 4)) %>% 
  mutate(month = str_sub(reported_date, start = 5, end = 6)) %>% 
  mutate(day = str_sub(reported_date, start = 7, end = 8)) %>% 
  mutate(date = str_c(year, month, day, sep = "/")) %>% 
  mutate(month_year = str_c(month, year, sep = "/")) %>% 
  filter(city == "Baltimore") 
```

```{r}
#making variables numeric

homicides_baltimore$year <- as.numeric(homicides_baltimore$year)
homicides_baltimore$month <- as.numeric(homicides_baltimore$month)
homicides_baltimore$day <- as.numeric(homicides_baltimore$day)
homicides_baltimore$date <- as.Date(homicides_baltimore$date)

```

```{r}
# making year month for Y axis

library(zoo)

hom_balt <- homicides_baltimore %>%
  mutate(yearmonth = as.yearmon(date, "%m/%Y"))

```


```{r}
hom_balt <- hom_balt %>%
  mutate(uid_new = str_sub(uid, start = 5, end = 10)) %>%
  mutate(obs = uid_new) 

hom_balt <- hom_balt %>% 
  mutate(season = case_when(
      month %in% 10:12 ~ "Winter",
      month %in%  1:3  ~ "Winter",
      month %in%  4:6  ~ "Summer",
      TRUE ~ "Summer"))

homicides_month <- hom_balt %>% 
  select(obs, city_name, year, date, yearmonth, month, season) %>% 
  group_by(yearmonth) %>% 
  summarize(monthly_homicides = n(),
            city_name = city_name,
            year = year,
            date = date,
            season = season,
            .groups = 'drop')

df <- homicides_month %>%
  distinct(yearmonth, .keep_all = TRUE)

```

```{r}
v_line <- "2015-04-12"
```


```{r, fig.width= 12, fig.height= 3}
df %>% 
  ggplot(aes(x = date, y = monthly_homicides)) +
  geom_bar(aes(fill = season), stat = "identity", width = 35,
           color = "darkgrey") +
  geom_smooth(se = FALSE, span = 0.1) + 
  scale_fill_manual(values = c("grey","lightblue")) +
  labs(x = "Date", y = "Monthly Homicides") +
  ggtitle("Homicides in Baltimore, MD") +
  geom_vline(aes(xintercept= as.numeric(as.Date(v_line))),
             linetype=3,col="red", size =1.5) +
  annotate("text", x = df$date[93], y = 41 - 0.1,
           label = "Arrest of \n Freddie Gray", color = "darkgrey") +
  theme_dark() +
  theme(legend.position = "bottom") 
```

